server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auth/**

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**

        - id: chat-ws
          uri: ws://chat-service:8082
          predicates:
              - Path=/ws/chat
          filters:
            - RemoveRequestHeader=Sec-WebSocket-Protocol

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
