server:
  port: 8082

spring:
  application:
    name: chat-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.paris.common.dto'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.paris.common.dto"

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Required so WebSockets are allowed through Spring Boot
#  web:
#    socket:
#      enabled: true

# ✅ FIX #3 — EXPOSE /ws/chat FOR WEBFLUX WEBSOCKET
  webflux:
    websocket:
      mapping:
        /ws/chat: chatWebSocketHandler

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
